name: Run Terraform Checks
on:
  pull_request:

env:
  TF_DIR: "terraform"


jobs:
  tfsyntax:
    name: Validate Terraform Syntax and Format
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run terraform validate
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init -backend=false
          terraform validate -no-color

      - name: Run terraform fmt
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform fmt -check -diff -recursive -no-color  

  tflint:
    name: Do Linting
    runs-on: ubuntu-latest
    container: ghcr.io/terraform-linters/tflint:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init linter
        working-directory: ${{ env.TF_DIR }}
        run: tflint --init

      - name: Run linter
        working-directory: ${{ env.TF_DIR }}
        run: tflint --recursive --no-color

  trivy:
    name: Run Security Scanning with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy IaC Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          limit-severities-for-sarif: true
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
